name: Android CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - splitlayout
      - '7.**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e

      - name: List playProd tasks
        run: ./gradlew tasks --all | grep -i playProd

      - name: Build APK
        env:
          GRADLE_OPTS: "-Xmx6g -XX:MaxMetaspaceSize=1g -Dkotlin.daemon.jvm.options=-Xmx3g"
        run: ./gradlew assemblePlayProdRelease --no-daemon --max-workers=4 --stacktrace

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: signal-arm64-release
          path: |
            app/build/outputs/apk/playProd/release/*arm64-v8a*.apk
            Signal-Android/build/outputs/apk/playProd/release/*arm64-v8a*.apk

      - name: Archive reports for failed build
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a0a
        with:
          name: reports
          path: |
            */build/reports
            **/build/reports
